### ISSUE TITLE
Запуск без прав админа

### ISSUE THREAD

**Issue by useragent23253** [MzHmO/NtlmThief#1]
Приветствую, спасибо за софт. Хотел бы поинтересоваться, что если запускать его из под доменного юзера, то хэш как я понимаю получаем не брутабельный? Он набит множеством нулей.
Пример: LSDEMO:35D59A727A7D32128F75E5959F647D71:010100000000000072E52F84F022DA018DA9A64764BA148B0000000008003000300000000000000000000000002000005D7CDEE3932DA9D60F49E7879
7628A45DE29441C26BEAB381E702AC3F9BA7FBF0A0010000000000000000000000000000000000009001C004C005300440045004D004F005C006C007300640065006D006F0038000000000000000000:1122334455
667788
Если же запускать с правада ЛА, то хэш выдается более короткий, как у вас на скринах.

**Comment by MzHmO** [comment]
Здравствуйте, это на хеш NetNTLMv2 похоже . Он тоже брутается. Просто медленнее

**Comment by useragent23253** [comment]
да, видно я чуть напутал. Спасибо за разъяснение!
